### ISSUE TITLE
FreeMP crashes while trying to scan filesystem

### ISSUE THREAD

**Issue by vi** [recoilme/freemp#14]
```
04-13 03:27:05.925 D/dalvikvm(16378): GC_CONCURRENT freed 1378K, 28% free 26840K/37208K, paused 2ms+2ms, total 29ms
04-13 03:27:06.315 W/AQuery  (16378): java.lang.NumberFormatException: Invalid int: ""
04-13 03:27:06.560 W/dalvikvm(16378): threadid=22: thread exiting with uncaught exception (group=0x41ae2c50)
04-13 03:27:06.560 W/System.err(16378): java.lang.RuntimeException: An error occured while executing doInBackground()
04-13 03:27:06.565 W/System.err(16378):     at android.os.AsyncTask$3.done(AsyncTask.java:300)
04-13 03:27:06.565 W/System.err(16378):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
04-13 03:27:06.565 W/System.err(16378):     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
04-13 03:27:06.565 W/System.err(16378):     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-13 03:27:06.565 W/System.err(16378):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-13 03:27:06.565 W/System.err(16378):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-13 03:27:06.565 W/System.err(16378):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-13 03:27:06.565 W/System.err(16378):     at java.lang.Thread.run(Thread.java:841)
04-13 03:27:06.565 W/System.err(16378): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
04-13 03:27:06.565 W/System.err(16378):     at org.freemp.droid.playlist.MakePlaylistFS.walk(MakePlaylistFS.java:236)
04-13 03:27:06.565 W/System.err(16378):     at org.freemp.droid.playlist.MakePlaylistFS.walk(MakePlaylistFS.java:111)
04-13 03:27:06.565 W/System.err(16378):     at org.freemp.droid.playlist.MakePlaylistFS.walk(MakePlaylistFS.java:111)
04-13 03:27:06.565 W/System.err(16378):     at org.freemp.droid.playlist.MakePlaylistFS.getAllTracks(MakePlaylistFS.java:68)
04-13 03:27:06.565 W/System.err(16378):     at org.freemp.droid.playlist.MakePlaylistAbstract.<init>(MakePlaylistAbstract.java:32)
04-13 03:27:06.565 W/System.err(16378):     at org.freemp.droid.playlist.MakePlaylistFS.<init>(MakePlaylistFS.java:38)
04-13 03:27:06.565 W/System.err(16378):     at org.freemp.droid.playlist.TaskGetPlaylist.doInBackground(TaskGetPlaylist.java:38)
04-13 03:27:06.565 W/System.err(16378):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-13 03:27:06.565 W/System.err(16378):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-13 03:27:06.565 W/System.err(16378):     ... 4 more
04-13 03:27:06.565 W/FlurryAgent(16378): Error logged: uncaught
04-13 03:27:06.565 W/FlurryAgent(16378): Ending session
04-13 03:27:06.570 E/AndroidRuntime(16378): FATAL EXCEPTION: AsyncTask #3
04-13 03:27:06.570 E/AndroidRuntime(16378): Process: org.freemp.droid, PID: 16378
04-13 03:27:06.570 E/AndroidRuntime(16378): java.lang.RuntimeException: An error occured while executing doInBackground()
04-13 03:27:06.570 E/AndroidRuntime(16378):     at android.os.AsyncTask$3.done(AsyncTask.java:300)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at java.lang.Thread.run(Thread.java:841)
04-13 03:27:06.570 E/AndroidRuntime(16378): Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
04-13 03:27:06.570 E/AndroidRuntime(16378):     at org.freemp.droid.playlist.MakePlaylistFS.walk(MakePlaylistFS.java:236)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at org.freemp.droid.playlist.MakePlaylistFS.walk(MakePlaylistFS.java:111)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at org.freemp.droid.playlist.MakePlaylistFS.walk(MakePlaylistFS.java:111)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at org.freemp.droid.playlist.MakePlaylistFS.getAllTracks(MakePlaylistFS.java:68)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at org.freemp.droid.playlist.MakePlaylistAbstract.<init>(MakePlaylistAbstract.java:32)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at org.freemp.droid.playlist.MakePlaylistFS.<init>(MakePlaylistFS.java:38)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at org.freemp.droid.playlist.TaskGetPlaylist.doInBackground(TaskGetPlaylist.java:38)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-13 03:27:06.570 E/AndroidRuntime(16378):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-13 03:27:06.570 E/AndroidRuntime(16378):     ... 4 more
04-13 03:27:06.575 W/ActivityManager( 3208):   Force finishing activity org.freemp.droid/.playlist.ActPlaylist
```

Note: XPrivacy is in use and may interfere with the application.

**Comment by vi** [comment]
With narrower directory it worked. It's too trivial to actually use unfortunately.

**Comment by recoilme** [comment]
fixed
